# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    git
    zsh-syntax-highlighting
    zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='nvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch $(uname -m)"

# Set personal aliases, overriding those provided by Oh My Zsh libs,
# plugins, and themes. Aliases can be placed here, though Oh My Zsh
# users are encouraged to define aliases within a top-level file in
# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
# - $ZSH_CUSTOM/aliases.zsh
# - $ZSH_CUSTOM/macos.zsh
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh


# --- Vi mode: hjkl editing on the command line ---
bindkey -v
export KEYTIMEOUT=1
export EDITOR=nvim
export VISUAL=nvim

autoload -Uz add-zle-hook-widget edit-command-line

# Cursor shape per mode (block=normal, beam=insert); p10k shows the text label
_vi_mode_cursor() {
  case $KEYMAP in
    vicmd) printf '\033[2 q' ;;
    *)     printf '\033[6 q' ;;
  esac
}
add-zle-hook-widget keymap-select _vi_mode_cursor
add-zle-hook-widget line-init      _vi_mode_cursor

# Ctrl-O inserts a newline instead of running the command.
# No ESC prefix, so it can't be absorbed into the Esc -> normal-mode switch.
_insert_newline() { LBUFFER+=$'\n'; }
zle -N _insert_newline
bindkey -M viins '^O' _insert_newline
bindkey -M vicmd '^O' _insert_newline

# Keep the emacs keys that make insert mode livable
bindkey -M viins '^?' backward-delete-char
bindkey -M viins '^H' backward-delete-char
bindkey -M viins '^A' beginning-of-line
bindkey -M viins '^E' end-of-line
bindkey -M viins '^K' kill-line
bindkey -M viins '^U' backward-kill-line
bindkey -M viins '^W' backward-kill-word
bindkey -M viins '^P' up-line-or-history
bindkey -M viins '^N' down-line-or-history

# Normal mode: / and ? search history; Ctrl-X Ctrl-E edits the line in $EDITOR.
# v is left as vi visual-mode so the VISUAL state stays reachable.
bindkey -M vicmd '/' history-incremental-search-backward
bindkey -M vicmd '?' history-incremental-search-forward
zle -N edit-command-line
bindkey -M viins '^X^E' edit-command-line
bindkey -M vicmd '^X^E' edit-command-line

# fzf sourced AFTER vi mode so Ctrl-R / Ctrl-T survive bindkey -v
[ -f /usr/share/fzf/key-bindings.zsh ] && source /usr/share/fzf/key-bindings.zsh
[ -f /usr/share/fzf/completion.zsh ] && source /usr/share/fzf/completion.zsh

export FZF_DEFAULT_OPTS='
--layout=reverse
--height=50%
--border=rounded
--margin=1,5
--prompt="🔍 "
--pointer="▶"
--color=bg+:#313244,fg:#CDD6F4,fg+:#F5E0DC,hl:#CBA6F7,hl+:#F38BA8
--color=info:#FAB387,prompt:#A6E3A1,pointer:#F5C2E7,marker:#F5C2E7,spinner:#FAB387
'

alias peaclock-spotify='peaclock --config ~/.peaclock/config/color_spotify'
alias peaclock-cyan='peaclock --config ~/.peaclock/config/color_cyan'
alias peaclock-dracula='peaclock --config ~/.peaclock/config/color_dracula_purple'
alias peaclock-emerald='peaclock --config ~/.peaclock/config/color_emerald'

alias unimatrix-safe='unimatrix -g black -c green -s 90 -a -n'

alias el='eza --icons -al'
export PATH="$HOME/.local/bin:$PATH"

alias glow='glow -w $(tput cols)'

# Piping into nvim keeps ANSI colors (baleia renders SGR as highlights).
# Only kicks in for a bare `cmd | nvim`; `nvim file` is untouched.
nvim() {
  if [[ ! -t 0 && $# -eq 0 ]]; then
    command nvim -c 'lua pcall(function() if vim.api.nvim_buf_line_count(0) <= 100000 then require("baleia").setup({}).once(0) else vim.notify("baleia: input too large; run :BaleiaColorize manually", vim.log.levels.WARN) end end)' -
  else
    command nvim "$@"
  fi
}

[[ ! -f ~/.config/zsh/caps-lock.zsh ]] || source ~/.config/zsh/caps-lock.zsh
